import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import TanStackProvider from '@/components/TanStackProvider';
import Header from '@/components/Header/';

import 'modern-normalize';
import './globals.css';

export const metadata: Metadata = {
  title: 'Rental Car',
  description: 'Generated by create next app',
};

const manropeFont = Manrope({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${manropeFont.variable}`}>
      <body>
        <Header />
        <TanStackProvider>
          <main>{children}</main>
        </TanStackProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
